apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: productcatalog
  namespace: productcatalogns
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: productcatalogservice # match with service.yaml -> labels
  endpoints:
    - port: metrics
      path: /metrics
      interval: 20s