apiVersion: v1
kind: ConfigMap
metadata:
  name: paymentservice-config
  namespace: paymentns
data:
  port: "{{ .Values.paymentservice.service.port }}"
  collector-addr: "localhost:1000"
  disable-profiler: "0"
  enable-tracing: "0"
  otel-service: ""
