apiVersion: v1
kind: Service
metadata:
  name: cartservice-svc
  labels:
    app: cartservice
  namespace: cartns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: cartservice-app # match with deployment (pod)
  ports:
  - name: grpc
    protocol: TCP
    port: 7070
    targetPort: 7070