apiVersion: v1
kind: Service
metadata:
  name: checkoutservice-svc
  labels:
    app: checkoutservice
  namespace: checkoutns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: checkoutservice-app
  ports:
  - name: grpc
    protocol: TCP
    port: 5050
    targetPort: 5050