apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis-cart
  namespace: redisns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: redis-app
  ports:
  - name: tcp-redis
    protocol: TCP
    port: {{ .Values.redis.service.port }}
    targetPort: {{ .Values.redis.service.port }}