# Context = root of project directory (for docker compose)

FROM node:24.18.0-alpine AS builder

RUN apk add --update --no-cache \
    python3 \
    make \
    g++

WORKDIR /app

COPY src/currencyservice/src/package*.json ./

RUN npm install --only=production

FROM alpine:3.23.4

RUN apk add --no-cache nodejs

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY src/currencyservice/src/. .

EXPOSE 7000

ENTRYPOINT [ "node", "server.js" ]
