apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    app: currencyservice
  namespace: currencyns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: currencyservice-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: currencyservice-app
    spec:
      containers:
      - name: currencyservice-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.currencyservice.service.port }}
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: currencyservice-config
              key: port
        - name: DISABLE_PROFILER
          valueFrom:
            configMapKeyRef:
              name: currencyservice-config
              key: disable-profiler
        - name: ENABLE_TRACING
          valueFrom:
            configMapKeyRef:
              name: currencyservice-config
              key: enable-tracing
        - name: COLLECTOR_SERVICE_ADDR
          valueFrom:
            configMapKeyRef:
              name: currencyservice-config
              key: collector-svc-addr
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 200m
            memory: 128Mi