apiVersion: v1
kind: ConfigMap
metadata:
  name: currencyservice-config
  namespace: currencyns
data:
  port: "7000"
  disable-profiler: "1"
  enable-tracing: "0"
  collector-svc-addr: "localhost:1000"