apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontendns
data:
  port: "8080"
  productcatalog-svc-addr: "productcatalogservice-svc.productcatalogns.svc.cluster.local:3550"
  currency-svc-addr: "currencyservice-svc.currencyns.svc.cluster.local:7000"
  cart-svc-addr: "cartservice-svc.cartns.svc.cluster.local:7070"
  checkout-svc-addr: "checkoutservice-svc.checkoutns.svc.cluster.local:5050"
  shipping-svc-addr: "shippingservice-svc.shippingns.svc.cluster.local:50051"
  enable-profiler: "0"
  enable-tracing: "0"
  listen-addr: "0.0.0.0"
  base-url: ""
