apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  labels:
    app: frontend
  namespace: frontendns
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080