cartservice:
  service:
    port: 7070

redis:
  service:
    port: 6379

checkoutservice:
  service:
    port: 5050

currencyservice:
  service:
    port: 7000

frontend:
  service:
    port: 8080

paymentservice:
  service:
    port: 50052

productcatalogservice:
  service:
    port: 3550

redis:
  service:
    port: 6379

shippingservice:
  service:
    port: 50051

ingress:
  certificateArn: "arn:aws:acm:us-east-1:211125424910:certificate/83e2ca90-89fd-4745-9ab4-2296cf5891a2"
  apphost: "harshitrajsinha.fun"
  argocdhost: "argocd.harshitrajsinha.fun"
  grafanahost: "grafana.harshitrajsinha.fun"
  prometheushost: "prometheus.harshitrajsinha.fun"
  subnetIdList: "subnet-04d0cb2766dae49b4,subnet-00915c1484d420e88"