apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: productcatalog
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: productcatalogservice-app
  endpoints:
    - port: metrics
      path: /metrics
      interval: 20s