name: CI pipeline - checkout, to run security scan, test, create and push checkout docker image

on:
  push:
    branches:
      # - main
      - dev
    paths:
      - 'src/checkoutservice/**'
      - '.github/workflows/**' # to be removed in production
permissions:
  contents: read

defaults:
  run:
    working-directory: src/checkoutservice

jobs:

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      
      ### Secrets scan
      
      - name: Secrets scan
        uses: gitleaks/gitleaks-action@v2.3.9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: '@harshitrajsinha'
      
      ### Vulnerability scan

      - name: Setup Go version '1.26.5'
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26.5'
      
      - name: Download dependencies
        working-directory: src/checkoutservice/src
        run: go mod download

      - name: Build to check errors
        working-directory: src/checkoutservice/src
        run: go build ./...
      
      - name: Vulnerability scan
        working-directory: src/checkoutservice/src
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.6.0
          govulncheck ./...
      
      ## File system scan (checkoutservice service):
      
      - name: Scan file system
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scanners: vuln,secret,misconfig
          scan-ref: src/checkoutservice
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL
      
      ### SBOM generation:
      # Note -> Here we are generating dependency graph directly to GitHub insights rather than separate artifact
      - name: SBOM generation
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          format: 'github'
          output: 'dependency-results.sbom.json'
          scan-ref: src/checkoutservice
          skip-setup-trivy: true
          github-pat: ${{ secrets.GITHUB_TOKEN }}

  linting:
    needs: [security-scan]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
      
      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          working-directory: src/checkoutservice/src
        
  unit-test:
    needs: [security-scan]
    # needs: [security-scan, linting]
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        
      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'
      
      - name: Download dependencies
        working-directory: src/checkoutservice/src
        run: go mod download

      - name: Build to check errors
        working-directory: src/checkoutservice/src
        run: go build ./...

      - name: Run go test
        working-directory: src/checkoutservice/src
        run: go test ./...

  image-build-release:
    needs: [security-scan]
    # needs: [security-scan, linting, unit-test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    env:
      IMAGE_NAME: checkoutns/checkout
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
        
      - name: Setup Go version '1.26.5'
        uses: actions/setup-go@v6.4.0
        with:
          go-version: '1.26.5'
      
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v4.1.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-actions-ecr-push
          aws-region: ${{ vars.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build and tag image
      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: ./src/checkoutservice
          file: ./src/checkoutservice/Dockerfile
          push: false
          load: true
          tags: |
            ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}

      ## Scan docker image using trivy
      - name: Docker image scan using Trivy
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1
          github-pat: ${{ secrets.GITHUB_TOKEN }}

      # SBOM generation
      # Note -> Here we are generating separate artifact for SBOM rather than for GitHub insights
      - name: Generate SBOM for docker image
        if: github.ref == 'refs/heads/main'
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'cyclonedx'
          output: 'docker-image.sbom.json'
          skip-setup-trivy: true
      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-docker-image-report
          path: 'docker-image.sbom.json'
      
      # Push image to ECR
      - name: Push image to ECR
        run: docker push ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/$IMAGE_NAME:$IMAGE_TAG
      